env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - airbnb
  - 'plugin:prettier/recommended'
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
